
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports:
      - "9092:9092"
      - "8081:8081"
    command:
      - redpanda
      - start
      - --mode dev-container
      - --advertise-kafka-addr redpanda:9092
  postgres:
    image: postgres:latest
    ports:
      - "55000:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8082:8080"          # UI на localhost:8082
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda

volumes:
  pgdata: